# Python warmup

Para esse conjunto de exercícios vamos utilizar o dataset [MovieLens 100k](https://grouplens.org/datasets/movielens/100k/)


Os conjuntos de dados do MovieLens foram coletados pelo GroupLens Research Project na Universidade de Minnesota.
 
Este conjunto de dados consiste em:
* 100.000 classificações (1-5) de 943 usuários em 1.682 filmes.
* Cada usuário classificou pelo menos 20 filmes.
* Informações demográficas simples para os usuários (idade, sexo, ocupação, CEP)

Os dados foram coletados por meio do site MovieLens (movielens.umn.edu) durante o período de sete meses a partir de 19 de setembro, 1997 a 22 de abril de 1998. Estes dados foram limpos - usuários que tiveram menos de 20 avaliações ou não tiveram dados demográficos completos informações foram removidas deste conjunto de dados. Descrições detalhadas de o arquivo de dados pode ser encontrado no final deste arquivo.

Utilizando esse Dataset responda as seguintes perguntas. Você deverá utilizar somente as bibliotecas padrões do python, i.e., nenhuma nova biblioteca deve ser adicionada para implementar suas soluções (**isso é um warmup de python!**)

#### Encontrar:
1. O(s) usuário(s) mais crítico(s) na avaliação de filmes.
    * Encontrar aquele id cujas notas são, em média, as menores;
1. O(s) filme(s) mais mal avaliado(s) pelos usuários.
1. O(s) filme(s) mais bem avaliado(s) pelos usuários.
1. Média de avaliação para cada gênero de filmes;
1. Avaliação média de filmes por ano. 
    * Listar qual o ano com a melhor média de avaliação de filmes;
1. Qual a ocupação mais propensa a dar más avaliações a filmes;
    * Encontrar a média de avaliação para cada ocupação de usuário e mostrar os menores e maiores valores


In [1]:
# Conforme orientação do professor, esse exercício será resolvido apenas com o pacote numpy e funções built-in python.
import numpy as np

In [2]:
# Importando os dados:
data = np.loadtxt('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.data')
print(data)

[[1.96000000e+02 2.42000000e+02 3.00000000e+00 8.81250949e+08]
 [1.86000000e+02 3.02000000e+02 3.00000000e+00 8.91717742e+08]
 [2.20000000e+01 3.77000000e+02 1.00000000e+00 8.78887116e+08]
 ...
 [2.76000000e+02 1.09000000e+03 1.00000000e+00 8.74795795e+08]
 [1.30000000e+01 2.25000000e+02 2.00000000e+00 8.82399156e+08]
 [1.20000000e+01 2.03000000e+02 3.00000000e+00 8.79959583e+08]]


## Explorando o conjunto de dados:

In [3]:
# Verificando o formato dos dados
np.shape(data)

(100000, 4)

In [4]:
# Verificando o tipo dos dados
print(data.dtype)

float64


In [5]:
type(data)

numpy.ndarray

## Q1. Usuários mais críticos (id cujas notas são, em média, as menores)

In [6]:
# Iremos declarar uma variável (id) que por meio da função np.unique irá encontrar os valores únicos da array.
ids = np.unique(data[:,0])
print(ids)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196.
 197. 

In [7]:
# Testando receber os ratings apenas para um user-id

# A variável indices receberá a fção filter(function, iterable) que
# retorna um iterador onde os itens são filtrados por meio de uma função para testar se o item é aceito ou não.

# Neste caso, a fção filter recebe a fção lambda que XXX quando a coluna 0 for igual a 100.
# O iterador buscará linha por linha em todo o comprimento (len) do dataset (data)

#indices = filter(lambda i: data[i,0]==100, [i for i in range(0,len(data))])
#print(list(indices))

In [8]:
# Obtendo as médias de ratings para cada user_id:
lst = list(map(lambda x: np.mean(data[x,2]) ,[np.array(list(filter(lambda i: data[i,0]==x, [i for i in range(0,len(data))]))) for x in ids]))
print(lst)

[3.610294117647059, 3.7096774193548385, 2.7962962962962963, 4.333333333333333, 2.874285714285714, 3.6350710900473935, 3.965260545905707, 3.7966101694915255, 4.2727272727272725, 4.206521739130435, 3.4640883977900554, 4.392156862745098, 3.09748427672956, 4.091836734693878, 2.875, 4.328571428571428, 3.0357142857142856, 3.88086642599278, 3.55, 3.1041666666666665, 2.670391061452514, 3.3515625, 3.6357615894039736, 4.323529411764706, 4.051282051282051, 2.94392523364486, 3.24, 3.721518987341772, 3.6470588235294117, 3.7674418604651163, 3.9166666666666665, 3.317073170731707, 3.7083333333333335, 4.05, 3.0, 3.8, 3.6491228070175437, 3.71900826446281, 3.772727272727273, 2.8857142857142857, 3.769230769230769, 3.726775956284153, 3.7104072398190047, 3.6490066225165565, 3.6041666666666665, 4.111111111111111, 3.64, 3.787878787878788, 2.683720930232558, 3.5416666666666665, 3.5652173913043477, 4.267857142857143, 3.8214285714285716, 3.6923076923076925, 3.2857142857142856, 3.641711229946524, 3.5, 3.837662337

In [9]:
# Ordenando a média de rating e relacionando aos user_ids:
ratings = np.array(lst)

sorted_ratings = np.sort(ratings)
ind_sorted = np.argsort(ratings)

result1 = np.transpose(np.stack((ids[ind_sorted],sorted_ratings)))

print('Os 10 usuários mais críticos e suas respectivas notas são:')
print(result1[0:5,:])

Os 10 usuários mais críticos e suas respectivas notas são:
[[181.           1.49195402]
 [405.           1.83446404]
 [445.           1.98518519]
 [685.           2.05      ]
 [774.           2.05803571]]


## Q2. O(s) filme(s) mais mal avaliado(s) pelos usuários.

In [43]:
# data2 = np.round(data, 2)
# data2 = np.round("%.2f" % data)
# print(data2)

In [11]:
# Número de títulos (filmes)
item = np.unique(data[:,1])
print(item)

[1.000e+00 2.000e+00 3.000e+00 ... 1.680e+03 1.681e+03 1.682e+03]


In [12]:
media_items = list(map(lambda a: np.mean(data[a,2]) ,[np.array(list(filter(lambda b: data[b,1]==a, [b for b in range(0,len(data))]))) for a in item]))
print(media_items)

[3.8783185840707963, 3.2061068702290076, 3.033333333333333, 3.550239234449761, 3.302325581395349, 3.576923076923077, 3.798469387755102, 3.9954337899543377, 3.8963210702341136, 3.831460674157303, 3.847457627118644, 4.385767790262173, 3.4184782608695654, 3.9672131147540983, 3.7781569965870307, 3.2051282051282053, 3.119565217391304, 2.8, 3.9565217391304346, 3.4166666666666665, 2.761904761904762, 4.151515151515151, 4.1208791208791204, 3.4482758620689653, 3.4436860068259385, 3.452054794520548, 3.1052631578947367, 3.931159420289855, 2.6666666666666665, 3.945945945945946, 3.6298701298701297, 3.7901234567901234, 3.4536082474226806, 2.7142857142857144, 2.1818181818181817, 2.1538461538461537, 2.25, 3.0083333333333333, 3.264367816091954, 2.8947368421052633, 3.081081081081081, 3.804054054054054, 3.0, 3.3417721518987342, 4.05, 3.5555555555555554, 3.601503759398496, 4.094017094017094, 3.3209876543209877, 4.3584905660377355, 3.45679012345679, 3.769230769230769, 2.953125, 3.2403846153846154, 3.7046979

In [35]:
# Ordenando a média de rating e relacionando aos user_ids:
piores = np.array(media_items)

sorted_piores = np.sort(piores)
item_sorted = np.argsort(piores)

result2 = np.transpose(np.stack((item[item_sorted], sorted_piores)))

print('Os filmes mais mal avaliados pelos usuários são:')
print(result2[:10,]) # Existem 70 títulos avaliados com nota 1.0

Os filmes mais mal avaliados pelos usuários são:
[[1.364e+03 1.000e+00]
 [1.561e+03 1.000e+00]
 [1.559e+03 1.000e+00]
 [1.557e+03 1.000e+00]
 [1.601e+03 1.000e+00]
 [4.370e+02 1.000e+00]
 [1.373e+03 1.000e+00]
 [1.548e+03 1.000e+00]
 [1.374e+03 1.000e+00]
 [1.546e+03 1.000e+00]]


In [33]:
# Corrigir número de casa decimais

In [6]:
# Relacionar com o título do filme

# Importando os dados:
# titulo = open('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.item', "r", encondig = "lantin-1")
# print(titulo.read())

titulo = open('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.item', encoding="latin-1")

In [8]:
print(titulo.read())

1|Toy Story (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)|0|0|0|1|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0
2|GoldenEye (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?GoldenEye%20(1995)|0|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0
3|Four Rooms (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Four%20Rooms%20(1995)|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0
4|Get Shorty (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Get%20Shorty%20(1995)|0|1|0|0|0|1|0|0|1|0|0|0|0|0|0|0|0|0|0
5|Copycat (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Copycat%20(1995)|0|0|0|0|0|0|1|0|1|0|0|0|0|0|0|0|1|0|0
6|Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)|01-Jan-1995||http://us.imdb.com/Title?Yao+a+yao+yao+dao+waipo+qiao+(1995)|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|0|0|0|0
7|Twelve Monkeys (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Twelve%20Monkeys%20(1995)|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|1|0|0|0
8|Babe (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Babe%20(1995)|0|0|0|0|1

In [106]:

numero = np.loadtxt('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.item',
                    encoding = 'latin-1',
                    usecols = (0),
                    dtype = 'int',
                    delimiter = "|")

nomes = np.loadtxt('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.item',
                    encoding = 'latin-1',
                    usecols = (1),
                    dtype = 'str',
                    delimiter = "|")

genero_bool = np.loadtxt('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.item',
                    encoding = 'latin-1',
                    usecols = (np.r_[5:24]),
                    dtype = 'bool',
                    delimiter = "|")

## Q3. O(s) filme(s) mais bem avaliado(s) pelos usuários.

In [35]:
# Ordenando a média de rating e relacionando aos user_ids:
melhores = np.array(media_items)

sorted_melhores = np.sort(melhores)
sorted_rev = sorted_melhores[::-1]
item_sorted_melhores = np.argsort(melhores)
item_rev = item_sorted_melhores[::-1]

result3 = np.transpose(np.stack((item[item_rev],sorted_rev)))

print('Os filmes mais bem avaliados pelos usuários são:')
print(result3[0:11,:])

Os filmes mais bem avaliados pelos usuários são:
[[1293.       5.   ]
 [1467.       5.   ]
 [1653.       5.   ]
 [ 814.       5.   ]
 [1122.       5.   ]
 [1599.       5.   ]
 [1201.       5.   ]
 [1189.       5.   ]
 [1500.       5.   ]
 [1536.       5.   ]
 [1449.       4.625]]


## Q4. Média de avaliação para cada gênero de filmes.

In [84]:
# # Importando os dados:
# genero = np.loadtxt('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.genre')
# print(genero)

genero = open('/home/hub/git-pessoal/Aulas_git_Ai2/5-Python/Jupyter_Notebook_Markdown/ml-100k/u.genre', "r")
print(genero.read())

unknown|0
Action|1
Adventure|2
Animation|3
Children's|4
Comedy|5
Crime|6
Documentary|7
Drama|8
Fantasy|9
Film-Noir|10
Horror|11
Musical|12
Mystery|13
Romance|14
Sci-Fi|15
Thriller|16
War|17
Western|18




In [44]:
# Testando

#concat = np.where(genero_bool[:,9]==True)

#print(nomes[concat])
#keep = gereni_bool[concat]